---
title: "Eric Fingar"
subtitle: "MA132 enrollment analyisis"
date:  "2023-10-04"
output: html_notebook
---

```{r}

library(tidyverse)
library(janitor)
library(here)

```

```{r}
df1=read_csv(here("data_raw","CU_ACAD_DEPT_WHEN_OFF_ENRL.csv")) %>% clean_names()

```

```{r}
df2 = df1 |> 
  filter(subject=="MA") |>
  select(-acad_org,-current_status,-course_id,-title) |>
  filter(component=="LEC", catalog %in% c(131,132) ) |>
  mutate(catalog=as.character(catalog)) |>
  separate_wider_delim(term_8," ",names = c("semester", "yr")) |>
  filter(!(semester=="Summer")) |>
  select(-subject) |>
  mutate(ay=((term_7-4000)/10) |> round()) |>
  select(-term_7,-yr,-component) |>
  slice_head(n=1,by=c("catalog","section","semester","ay"))|>
  select(-instructor) |>
  summarise(tot_enrl = sum(tot_enrl), .by=c("catalog","semester","ay")) |>
  pivot_wider(id_cols = ay,names_from = c("semester","catalog"),values_from = tot_enrl) |>
  clean_names() |>
  select(-spring_131)
  
```